
/**
 * 
 * AUTH RELATED
 * 
 */

export const RECEIVED_ACCESS_TOKEN = 'RECEIVED_ACCESS_TOKEN'
export const INVALIDATE_USER_SESSION =
'INVALIDATE_USER_SESSION'
export const RECEIVED_USER_PROFILE =
'RECEIVED_USER_PROFILE'

