export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN'
export const REMOVE_ACCESS_TOKEN = 'LOGOUT'

export const REQUESTING_USER_DATA = 'REQUESTING_USER_DATA'
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE'

export const UPDATE_USER_TRACK_LIST = 'UPDATE_USER_TRACK_LIST'
export const RECEIVE_SONG_DATA = 'RECEIVE_SONG_DATA'




// NEW 
export const RECEIVED_ACCESS_TOKEN = 'RECEIVED_ACCESS_TOKEN'
export const INVALIDATE_USER_SESSION =
'INVALIDATE_USER_SESSION'
export const RECEIVED_USER_PROFILE =
'RECEIVED_USER_PROFILE'